### ISSUE TITLE
This repo appears to be unmaintained

### ISSUE THREAD

**Issue by nfirvine** [razorsedge/puppet-network#119]
The maintainer hasn't been active since March 2016 (six months ago as of writing).

**Comment by razorsedge** [comment]
At the moment I am having a severe lack-of-time.  Of course, when I do have the time, it tends to be accompanied by a lack of energy. :-(

**Comment by razorsedge** [comment]
I am presently triaging all 47 outstanding issues/PRs.

**Comment by razorsedge** [comment]
Issues triaged and PRs merged.
