### ISSUE TITLE
PEERDNS=no should not block DNS1 and DNS2

### ISSUE THREAD

**Issue by KedneckInc** [razorsedge/puppet-network#129]
[From the RHEL 7 Manual:](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_Command_Line_Interface.html#sec-Configuring_a_Network_Interface_Using_ifcg_Files)

> To configure an interface to use particular DNS servers, set `PEERDNS=no` as described above and add lines as follows to the ifcfg file:
>
>     DNS1=ip-address
>     DNS2=ip-address
>
> where ip-address is the address of a DNS server. This will cause the network service to update /etc/resolv.conf with the DNS servers specified.

Yet the code in the ifcfg-eth.epp template says (indentation added for clarity):

    <% if !@peerdns %>PEERDNS=no
    <% else %>PEERDNS=yes
        <% if @dns1_real %>DNS1=<%= @dns1_real %>
        <% end -%>
        <% if @dns2_real %>DNS2=<%= @dns2_real %>
        <% end -%>
        <% if @domain %>DOMAIN="<%= @domain %>"
        <% end -%>
    <% end -%>

So the only way you can set DNS1 and DNS2 is if PEERDNS is yes?  This is not the way the documentation says it should work, and it's not the way it works in real life.

**Comment by razorsedge** [comment]
Linking to #60 and #116

**Comment by razorsedge** [comment]
Fixed in Puppet Forge release [razorsedge/network 3.10.0](https://forge.puppet.com/razorsedge/network/3.10.0/).
