### ISSUE TITLE
noaliasrouting option for single network alias

### ISSUE THREAD

**Issue by rgtx** [razorsedge/puppet-network#56]
Had a case where we needed NO_ALIASROUTING=yes set for a single alias (instead of a range).

Went ahead and just added this to alias.pp and ifcfg-alias.erb:

<pre>
--- a/modules/network/manifests/alias.pp
+++ b/modules/network/manifests/alias.pp
@@ -10,6 +10,7 @@
 #   $netmask   - required
 #   $gateway   - optional
 #   $userctl   - optional - defaults to false
+#   $noaliasrouting  - optional - defaults to false
 #
 # === Actions:
 #
@@ -38,12 +39,14 @@ define network::alias (
   $gateway = '',
   $ipv6address = '',
   $ipv6gateway = '',
-  $userctl = false
+  $userctl = false,
+  $noaliasrouting = false
 ) {
   # Validate our data
   if ! is_ip_address($ipaddress) { fail("${ipaddress} is not an IP address.") }
   # Validate our booleans
   validate_bool($userctl)
+  validate_bool($noaliasrouting)
 
   network_if_base { $title:
     ensure       => $ensure,

--- a/modules/network/templates/ifcfg-alias.erb
+++ b/modules/network/templates/ifcfg-alias.erb
@@ -13,4 +13,7 @@ TYPE=Ethernet
 <% end -%>
 <% if @userctl %>USERCTL=yes
 <% end -%>
+<% if !@noaliasrouting %>NO_ALIASROUTING=no
+<% else %>NO_ALIASROUTING=yes
+<% end -%>
 NM_CONTROLLED=no
</pre>

**Comment by razorsedge** [comment]
@rgtx Would you mind submitting that as a PR against the develop branch? Perhaps with some info in the README.md?
