### ISSUE TITLE
Bond interface is failing

### ISSUE THREAD

**Issue by kuduka** [razorsedge/puppet-network#66]
Bond interface is failing with the follow definition/error, seems that peerdns is not defined for bond interfaces so template is failing looking up peerdns variable:

<% if !peerdns.empty? %><% if dns1.empty? %><% if dns2.empty? %>PEERDNS=no

    ::network::bond::static { $name:
      ipaddress    => $ipaddress,
      netmask      => $mask,
      gateway      => $gateway,
      mtu          => "1500",
      bonding_opts => "mode=1 primary=$primary_name arp_interval=1000 arp_ip_target=$gateway",
      ensure       => "up",
    }

Debug: template[/etc/puppet/modules/network/templates/ifcfg-eth.erb]: Bound template variables for /etc/puppet/modules/network/templates/ifcfg-eth.erb in 0.00 seconds
Error: Failed to parse template network/ifcfg-eth.erb:
  Filepath: /etc/puppet/modules/network/templates/ifcfg-eth.erb
  Line: 23
  Detail: undefined method `empty?' for false:FalseClass
 at /etc/puppet/modules/network/manifests/init.pp:97 on node testnode
Error: Failed to parse template network/ifcfg-eth.erb:
  Filepath: /etc/puppet/modules/network/templates/ifcfg-eth.erb
  Line: 23
  Detail: undefined method `empty?' for false:FalseClass
 at /etc/puppet/modules/network/manifests/init.pp:97 on node testnode

Versions of puppet/facter:

  puppet-3.7.5-1.el7.noarch
  facter-2.4.3-1.el7.x86_64

**Comment by razorsedge** [comment]
@kuduka What version of the razorsedge/network module are you using?
