### ISSUE TITLE
Service network enable changed on every run

### ISSUE THREAD

**Issue by Wernervdmerwe** [razorsedge/puppet-network#82]
I get this on every run:

Notice: /Stage[main]/Network/Service[network]/enable: enable changed 'false' to 'true'

Puppet agent 4.2.1 and 4.2.3 on CentOS 7.1, PE 2015
This is on each of the production servers, but they serve other content fine, so I know the service is up

**Comment by claflico** [comment]
I am getting this too on CentOS 7.2, razorsedge/network', '3.6.0', & puppet version:

puppetserver-2.2.1-1.el7.noarch
puppetexplorer-2.0.0-1.noarch
puppetdb-termini-3.2.2-1.el7.noarch
puppetdb-3.2.2-1.el7.noarch
puppetlabs-release-pc1-1.0.0-1.el7.noarch
puppet-agent-1.3.2-1.el7.x86_64

**Comment by razorsedge** [comment]
Linked to #65.

**Comment by razorsedge** [comment]
Merged in efec40e35526b65240c0b8d0944a133dcb5e6d1f.
