### ISSUE TITLE
Same variable twice in init.pp

### ISSUE THREAD

**Issue by newbenji** [razorsedge/puppet-network#92]
120: $linkdelay       = undef,
  121: $scope           = undef,
  122: $linkdelay       = undef,

$linkdelay is there 2 times

**Comment by razorsedge** [comment]
Looks like I added that in commit 2cd3ca2e02ba5350416c78281adb093a9260e3b7.

**Comment by razorsedge** [comment]
Fixed in release 3.7.0.
