### ISSUE TITLE
Add bootproto to network::alias

### ISSUE THREAD

**Issue by jnancel** [razorsedge/puppet-network#95]
Hello,

Currently bootproto is not available in network::alias, would it be possible to add it? From my point of view, the following patch should be sufficient ( but maybe I'm missing something ) : 

```
--- alias.pp.orig       2016-03-24 12:13:14.792659898 +0100
+++ alias.pp    2016-03-24 12:12:31.239631432 +0100
@@ -38,7 +38,8 @@
   $gateway = undef,
   $ipv6address = undef,
   $ipv6gateway = undef,
-  $userctl = false
+  $userctl = false,
+  $bootproto = 'none',
 ) {
   # Validate our data
   if ! is_ip_address($ipaddress) { fail("${ipaddress} is not an IP address.") }
@@ -53,7 +54,7 @@
     ipv6address  => $ipv6address,
     ipv6gateway  => $ipv6gateway,
     macaddress   => '',
-    bootproto    => 'none',
+    bootproto    => $bootproto,
     userctl      => $userctl,
     mtu          => '',
     ethtool_opts => '',
```

Thanks

Jeremy

**Comment by razorsedge** [comment]
@jnancel What are you looking to do with BOOTPROTO on an alias?

**Comment by jnancel** [comment]
Hello Mike,

My assumption was that when bootproto=none, then the interface does not start, for interface or alias.

Your question made me wonder whether my assumptions were right or not and it turns out they’re not. bootproto=none is the same as static as long as you specify IPADDRESS and NETMASK.

Sorry about the bothering, I didn’t look enough beforehand. :’(

Best regards

Jeremy
